spring:
  application:
    name: api-gateway
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
  redis:
    database: 1
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 100
        max-idle: 20
        min-idle: 10
server:
  port: 8080